### ISSUE TITLE
Esclarecimento

### ISSUE THREAD

**Issue by stdonato** [everaldoscabral/script_banco_zabbix#1]
No caso de um restore será criada toda a estrutura do banco e apenas os dados das tabelas ignoradas não serão importados, já que não foram salvos, correto?

**Comment by everaldoscabral** [comment]
> No caso de um restore será criada toda a estrutura do banco e apenas os dados das tabelas ignoradas não serão importados, já que não foram salvos, correto?

Sim, mas lembrando que são dois arquivos gerados. O primeiro ele faz apenas o backup da estrutura do banco (tabelas) sem dados, depois de feito isso, ele realiza propriamente o backup do banco ignorando as tabelas maiores. No Restore, segue a sequência de restaurar a estrutura do banco e depois o Restore dos dados.

**Comment by stdonato** [comment]
Obrigado pelo esclarecimento e pelo script.
