### ISSUE TITLE
#1062 - Duplicate entry '2' for key 'actions.PRIMARY'

### ISSUE THREAD

**Issue by HorselessName** [everaldoscabral/script_banco_zabbix#2]
Olá.

Eu estou utilizando seu script para fazer o backup do meu banco de dados, em uma instalação nova do Zabbix na mesma versão ao importar ele dá o erro #1062 - Duplicate entry '2' for key 'actions.PRIMARY'...

Sabe alguma forma de contornar esse erro?

**Comment by everaldoscabral** [comment]
Olhe o campo de sugestão no How to. ;)
